[workspace]
members = [
    "bvhtracer",
    "bvhtracer_demos",
    "example_trippy_teapots",
    "example_big_ben_clock",
    "example_cube",
    "example_quad",
    "example_sixteen_armadillos",
    "example_two_armadillos",
    "example_trippy_teapots",
    "examples",
]

