[package]
name = "tiled_array"
version = "0.1.0"
edition = "2021"

[dependencies]


[dev-dependencies]
criterion = "0.3.5"
rand = "0.8.5"
rand_isaac = "0.3.0"

[[bench]]
name = "bench_array_memory_access"
harness = false

